excerpt_separator: ""
markdown: kramdown
extensions: ['smart', 'tables', 'with_toc_data', 'fenced_code_blocks']
url: http://pumiko.pl
title: pumiko
tagline: Historia zakręconego projektu
description: Blog pumiko
paginate: 8
email:  pumiko@pumiko.pl
author: Pumiko

show_social_icons: true
show_sharing_icons: true
disqus_shortname: pumiko

# Google services
google_analytics: UA-73762910-1
google_verification:

# Social icons
github_username: pumiko
bitbucket_username:
stackoverflow_id:
twitter_username: pumi_ko
facebook_username: pepiniera.net
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:

# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text       :
  share_buttons:
    text:         'Przeczytałeś? Udostępnij!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post       :
    minute_read: 'min czytania'
  contact    :
    email      : 'E-mail'
    content    : 'Wiadomość'
    subject    : 'Wiadomość z bloga!'
    submit     : 'Wyślij'
    ajax       :
      sending    : 'Wysyłam...'
      sent       : 'Wysłano!'
      error      : 'Błąd!'
  thanks     : 'Odpowiem najszybciej jak to tylko możliwe :)'

gems:
  - jekyll-paginate
  - jekyll-sitemap
