excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://pumiko.github.io
title: pumiko
tagline: A log of everyday life
description: My awesome new site
paginate: 5

# Social icons
github_username: pumiko
bitbucket_username:
stackoverflow_id:
twitter_username: 
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
