excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://pumiko.github.io
title: pumiko
tagline: A log of everyday life
description: My awesome new site
paginate: 5
email:  stec.magda@gmail.com
author: Pumiko

show_social_icons: true
show_sharing_icons: true
disqus_shortname: pumiko

# Social icons
github_username: pumiko
bitbucket_username:
stackoverflow_id:
twitter_username: 
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:

# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text       :
  post       :
    minute_read: 'min czytania'
  contact    :
    email      : 'e-mail'
    content    : 'Treść'
    subject    : 'Wiadomość z bloga!'
    submit     : 'Wyślij'
    ajax       :
      sending    : 'Wysyłam...'
      sent       : 'Wysłano!'
      error      : 'Błąd!'
  thanks     : 'Dziękuję za kontakt!'
